export const TRIP_CATEGORIES = [
    { id: 'ธรรมชาติ', emoji: '🌳', label: 'ธรรมชาติ' },
    { id: 'ทะเล', emoji: '🏖️', label: 'ทะเล' },
    { id: 'ภูเขา', emoji: '⛰️', label: 'ภูเขา' },
    { id: 'แคมป์ปิ้ง', emoji: '⛺', label: 'แคมป์ปิ้ง' },
    { id: 'ผจญภัย', emoji: '🧗', label: 'ผจญภัย' },
    { id: 'กีฬา', emoji: '🏃', label: 'กีฬา' },
    { id: 'ปาร์ตี้', emoji: '🎉', label: 'ปาร์ตี้' },
    { id: 'วัฒนธรรม', emoji: '🏯', label: 'วัฒนธรรม' },
    { id: 'ประวัติศาสตร์', emoji: '🏛️', label: 'ประวัติศาสตร์' },
    { id: 'ถ่ายรูป', emoji: '📸', label: 'ถ่ายรูป' },
    { id: 'คาเฟ่', emoji: '☕', label: 'คาเฟ่' },
    { id: 'อาหาร', emoji: '🍜', label: 'อาหาร' },
    { id: 'ช้อปปิ้ง', emoji: '🛍️', label: 'ช้อปปิ้ง' },
    { id: 'จิตอาสา', emoji: '🤝', label: 'จิตอาสา' },
    { id: 'ครอบครัว', emoji: '👨‍👩‍👧‍👦', label: 'ครอบครัว' },
    { id: 'อื่นๆ', emoji: '✨', label: 'อื่นๆ' },
];
